Leafground_url=https://leafground.com/button.xhtml
Leaftaps_url=http://leaftaps.com/opentaps/
Leafground_chekBoxurl=https://leafground.com/checkbox.xhtml
Leafground_radioBtnUrl=https://www.leafground.com/radio.xhtml

invalidUsr=demoManagersales
validUsr=Demosalesmanager

invalidPwd=dscUY9
validPwd=crmsfa